describe('User Auth', () => {
    it('Consumer sign-up test', () => {
        cy.visit('http://localhost:3000/')
        cy.clearCookies()

        cy.contains('Sign Up').click()
        cy.url().should('include', '/signup')

        cy.get('input[id=formName]')
            .type('Consumer Auth Test')
            .should('have.value', 'Consumer Auth Test')
        cy.get('input[id=formEmail]')
            .type('consumer@gmail.com')
            .should('have.value', 'consumer@gmail.com')
        cy.get('input[id=formPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')
        cy.get('input[id=formConfPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')

        cy.get('input[id=formGridAddress1]')
            .type('555 Street Name')
            .should('have.value', '555 Street Name')
        cy.get('input[id=formGridCity]')
            .type('San Francisco')
            .should('have.value', 'San Francisco')
        cy.get('select[id=formGridState]')
            .select('CA')
            .should('have.value', 'CA')
        cy.get('input[id=formGridZip]')
            .type('94114')
            .should('have.value', '94114')

        cy.get('input[id=consumerRadio]')
            .check()
            .should('have.value', 'Consumer')

        cy.get('button[type=submit]').click()
        cy.get('.navbar-right-logged-in').contains('consumer@gmail.com')
    }),
    it('Consumer login', () => {
        cy.visit('http://localhost:3000/')
        cy.clearCookies()

        cy.contains('Sign Up').click()
        cy.url().should('include', '/signup')

        cy.get('input[id=formName]')
            .type('Consumer Login Test')
            .should('have.value', 'Consumer Login Test')
        cy.get('input[id=formEmail]')
            .type('another.consumer@gmail.com')
            .should('have.value', 'another.consumer@gmail.com')
        cy.get('input[id=formPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')
        cy.get('input[id=formConfPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')

        cy.get('input[id=formGridAddress1]')
            .type('555 Street Name')
            .should('have.value', '555 Street Name')
        cy.get('input[id=formGridCity]')
            .type('San Francisco')
            .should('have.value', 'San Francisco')
        cy.get('select[id=formGridState]')
            .select('CA')
            .should('have.value', 'CA')
        cy.get('input[id=formGridZip]')
            .type('94114')
            .should('have.value', '94114')

        cy.get('input[id=consumerRadio]')
            .check()
            .should('have.value', 'Consumer')

        cy.get('button[type=submit]').click()

        cy.get('a[id=nav-profile]').click()
        cy.contains('Sign Out').click()

        cy.contains('Login').click()
        cy.url().should('include', '/signin')

        cy.get('input[id=formEmail]')
            .type('another.consumer@gmail.com')
            .should('have.value', 'another.consumer@gmail.com')
        cy.get('input[id=formPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')

        cy.get('button[type=submit]').click()
        cy.get('.navbar-right-logged-in').contains('another.consumer@gmail.com')
    }),
    it('Farmer sign-up test', () => {
        cy.visit('http://localhost:3000/')
        cy.clearCookies()

        cy.contains('Sign Up').click()
        cy.url().should('include', '/signup')

        cy.get('input[id=formName]')
            .type('Farmer Auth Test')
            .should('have.value', 'Farmer Auth Test')
        cy.get('input[id=formEmail]')
            .type('farmer@gmail.com')
            .should('have.value', 'farmer@gmail.com')
        cy.get('input[id=formPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')
        cy.get('input[id=formConfPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')

        cy.get('input[id=formGridAddress1]')
            .type('555 Street Name')
            .should('have.value', '555 Street Name')
        cy.get('input[id=formGridCity]')
            .type('San Francisco')
            .should('have.value', 'San Francisco')
        cy.get('select[id=formGridState]')
            .select('CA')
            .should('have.value', 'CA')
        cy.get('input[id=formGridZip]')
            .type('94114')
            .should('have.value', '94114')

        cy.get('input[id=farmerRadio]')
            .check()
            .should('have.value', 'Farmer')

        cy.get('button[type=submit]').click()
        cy.get('.navbar-right-logged-in').contains('farmer@gmail.com')
    }),
    it('Farmer login', () => {
        cy.visit('http://localhost:3000/')
        cy.clearCookies()

        cy.contains('Sign Up').click()
        cy.url().should('include', '/signup')

        cy.get('input[id=formName]')
            .type('Farmer Login Test')
            .should('have.value', 'Farmer Login Test')
        cy.get('input[id=formEmail]')
            .type('another.farmer@gmail.com')
            .should('have.value', 'another.farmer@gmail.com')
        cy.get('input[id=formPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')
        cy.get('input[id=formConfPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')

        cy.get('input[id=formGridAddress1]')
            .type('555 Street Name')
            .should('have.value', '555 Street Name')
        cy.get('input[id=formGridCity]')
            .type('San Francisco')
            .should('have.value', 'San Francisco')
        cy.get('select[id=formGridState]')
            .select('CA')
            .should('have.value', 'CA')
        cy.get('input[id=formGridZip]')
            .type('94114')
            .should('have.value', '94114')

        cy.get('input[id=farmerRadio]')
            .check()
            .should('have.value', 'Farmer')

        cy.get('button[type=submit]').click()

        cy.get('a[id=nav-profile]').click()
        cy.contains('Sign Out').click()

        cy.contains('Login').click()
        cy.url().should('include', '/signin')

        cy.get('input[id=formEmail]')
            .type('another.farmer@gmail.com')
            .should('have.value', 'another.farmer@gmail.com')
        cy.get('input[id=formPassword]')
            .type('123!@#123')
            .should('have.value', '123!@#123')

        cy.get('button[type=submit]').click()
        cy.get('.navbar-right-logged-in').contains('another.farmer@gmail.com')
    })
})